version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hl4_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: langs
      MYSQL_USER: langs
      MYSQL_PASSWORD: langs123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - hl4_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:latest
    container_name: hl4_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "16379:6379"
    networks:
      - hl4_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  backend:
    build:
      context: ./hl4-backend
      dockerfile: Dockerfile
    container_name: hl4_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/langs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: langs
      SPRING_DATASOURCE_PASSWORD: langs123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "18080:8080"
    networks:
      - hl4_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  dashboard:
    build:
      context: ./hl4-dashboard
      dockerfile: Dockerfile
    container_name: hl4_dashboard
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:18080
    ports:
      - "13000:80"
    networks:
      - hl4_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  homepage:
    build:
      context: ./hl4-homepage
      dockerfile: Dockerfile
    container_name: hl4_homepage
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:18080
    ports:
      - "13001:80"
    networks:
      - hl4_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  hl4_network:
    driver: bridge

volumes:
  mysql_data:
    name: hl4_mysql_data
  redis_data:
    name: hl4_redis_data
