server:
  port: 3307
  compression:
    enabled: true
    min-response-size: 512
  error:
    include-stacktrace: always
    include-exception: true
spring:
  main:
    allow-circular-references: true
  application:
    name: newlangs
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dns1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: dns1
      password: dns1
  data:
    redis:
      database: 0
      host: localhost
#      password:
      port: 6379
      timeout: 3s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
    token-name: accessToken
    timeout: -1
    active-timeout: -1
    is-concurrent: true
    is-share: false
    token-style: tik
    is-log: false
